# -*- coding: utf-8 -*-
"""simple-temp-converter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12hIuiajXkmy0n4gFfYD7DKV0t5vkFOtV
"""

# Write your code here
temp = float(input('What is the temperature?: '))
from_unit = input('What temperature it is from?: (C/K/F)').upper() # isi dg yg ada di valid_unit aja
to_unit = input('Which temperature you want to convert to?: (C/K/F)').upper() # isi dg yg ada di valid_unit aja

valid_unit = ['C','K','F']

# jawaban
if from_unit not in valid_unit or to_unit not in valid_unit:
   hasil = print("Please input correctly")
else:
  if(from_unit == 'C' and to_unit == 'F'):
    hasil = (temp*9/5)+32
  if(from_unit == 'F' and to_unit == 'C'):
    hasil = 5/9*(temp-32)
  if(from_unit == 'C' and to_unit == 'K'):
    hasil = temp + 273.15
  if(from_unit == 'K' and to_unit == 'C'):
    hasil = temp - 273.15
  if(from_unit == 'K' and to_unit == 'F'):
    hasil = (temp - 273.15)*1.8 + 32
  if(from_unit == 'F' and to_unit == 'K'):
    hasil = (temp - 32)*5/9 + 273.15
  if((from_unit == 'F' and to_unit == 'F') or (from_unit == 'K' and to_unit == 'K') or (from_unit == 'C' and to_unit == 'C')):
    hasil = temp

  hasil = round(hasil, 2)
  print(f'{temp}{from_unit} is equal to {hasil}{to_unit}')